stages:
  - build
  - test

cache: 
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"
    

build_job:
  stage: build
  script: 
    - ./mvnw compile
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_JOB_NAME/.m2/repository
      -Dorg.slf4J.simpleLogger.log.org.apache.maven.cli.transfer.Slf4MavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
      --batch-mode --errors --fail-at-end
      --show-version -DinstallAtEnd=true
      -DdeployAtEnd=true
  image: eclipse-temurin:17-alpine

test_job:
  stage: test
  script:
    - pwd
    - ./mvnw test
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  image: eclipse-temurin:17-alpine

    

