#Utilise une image de base maven et openjdk17
FROM maven 3.8.4-openjdk-17-slim as builder

#installer docker afin que le conteneur puisse construire des images docker
USER root
RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl gnupg lsb-release && \
  curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
  echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list && \
  apt-get update -qq && \
  apt-get install -y --no-install-recommends docker-ce docker-ce-cli containerd.io && \
  apt-get clean

